language: objective-c
osx_image: xcode7

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=ObjectMapper.xcworkspace
  matrix:
    - SCHEME="ObjectMapper-iOS" SDK="iphonesimulator"
    - SCHEME="ObjectMapper-Mac" SDK="macosx"  

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  # - brew update
  # - brew outdated xctool || brew upgrade xctool

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -workspace $XCODE_WORKSPACE -scheme "$SCHEME" -sdk "$SDK" test | xcpretty -c

notifications:
  email: false